1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: -1
  num_trials: 50
  parameter_constraints: []
  parameters:
  - name: model
    type: choice
    values:
    - complex
    - transe
    - rotate
    - rescal
    - distmult
  - bounds:
    - 0.0
    - 1.0
    name: train.optimizer.default.args.lr
    type: range
  - bounds:
    - 1.0e-08
    - 1.0
    log_scale: true
    name: train.optimizer.default.args.weight_decay
    type: range
  - name: lookup_embedder.dim
    type: choice
    values:
    - 100
    - 200
    - 300
  sobol_seed: 0
complex:
  class_name: ComplEx
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    type: lookup_embedder
console:
  format: {}
  quiet: false
conve:
  2D_aspect_ratio: 2
  class_name: ConvE
  convolution_bias: true
  entity_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  feature_map_dropout: 0.2
  filter_size: 3
  padding: 0
  projection_dropout: 0.3
  relation_embedder:
    +++: +++
    dropout: 0.2
    type: lookup_embedder
  round_dim: false
  stride: 1
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      size: 1169
      split_type: test
      type: triples
    test_without_unseen:
      filename: test_without_unseen.del
      size: 1169
      split_type: test
      type: triples
    train:
      filename: train.del
      size: 8218
      split_type: train
      type: triples
    train_sample:
      filename: train_sample.del
      size: 1169
      split_type: train
      type: triples
    valid:
      filename: valid.del
      size: 1169
      split_type: valid
      type: triples
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 1169
      split_type: valid
      type: triples
  name: wordcraft_data
  num_entities: 700
  num_relations: 2
  pickle: true
distmult:
  class_name: DistMult
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    type: lookup_embedder
entity_ranking:
  chunk_size: -1
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: false
    relation_type: false
  tie_handling: rounded_mean_rank
eval:
  batch_size: 100
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- complex
- transe
- rotate
- rescal
- distmult
- reciprocal_relations_model
job:
  device: cuda
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 300
  dropout: 0.0
  initialize: normal_
  initialize_args:
    +++: +++
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: rescal
modules:
- kge.job
- kge.model
- kge.model.embedder
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: auto
  num_samples:
    o: -1
    p: 0
    s: 3
  sampling_type: uniform
  shared: false
  shared_type: default
  with_replacement: true
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1
reciprocal_relations_model:
  base_model:
    +++: +++
    type: conve
  class_name: ReciprocalRelationsModel
rescal:
  class_name: Rescal
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    dim: -1
    type: lookup_embedder
rotate:
  class_name: RotatE
  entity_embedder:
    +++: +++
    type: lookup_embedder
  l_norm: 1.0
  normalize_phases: true
  relation_embedder:
    +++: +++
    dim: -1
    initialize: uniform_
    initialize_args:
      uniform_:
        a: -3.14159265359
        b: 3.14159265359
    type: lookup_embedder
search:
  device_pool: []
  num_workers: 1
  on_error: abort
  type: ax_search
train:
  abort_on_nan: true
  auto_correct: false
  batch_size: 100
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: .nan
  lr_scheduler: ''
  lr_scheduler_args:
    +++: +++
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.1000660015270114
        weight_decay: 9.492420806079791e-07
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: KvsAll
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
transe:
  class_name: TransE
  entity_embedder:
    +++: +++
    type: lookup_embedder
  l_norm: 1.0
  relation_embedder:
    +++: +++
    type: lookup_embedder
user:
  +++: +++
valid:
  early_stopping:
    patience: 5
    threshold:
      epochs: 0
      metric_value: 0.0
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
